ALTER TABLE "SystemConfig"
  ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "SystemConfig"
  ADD COLUMN IF NOT EXISTS "reservation_window_hr" INTEGER NOT NULL DEFAULT 24;

ALTER TABLE "SystemConfig"
  ADD COLUMN IF NOT EXISTS "low_stock_threshold" INTEGER NOT NULL DEFAULT 2;

ALTER TABLE "SystemConfig"
  ADD COLUMN IF NOT EXISTS "never_returned_days" INTEGER NOT NULL DEFAULT 60;

ALTER TABLE "SystemConfig"
  ADD COLUMN IF NOT EXISTS "reminder_days_before_due" INTEGER NOT NULL DEFAULT 3;
